### ISSUE TITLE
여기 탭에 질문해도 되나요?

### ISSUE THREAD

**Issue by dlddnd** [narongchan/getCoVaccine#1]
refeat= setInterval(jabja,3500);
setTimeout(init, 3000);

위 두가지 시간조정이 어떻게 다른지 궁금합니다!

**Comment by narongchan** [comment]
아 네 여기에 질문하셔도 됩니다! 
refeat은 업데이트시키는 거였구요! 
setTimeout 저거는 처음에 백신매크로 작동한다는 alert메시지 보내는 용도였습니다! :-) 
곧 크롬 익스텐션으로 내보낼 예정입니다:)

**Comment by dlddnd** [comment]
@narongchan 프로그램 만드느라 고생이 많으십니다
네이버 잔여백신지도상에 표시된 병원에서만 작동하는거죵?

**Comment by narongchan** [comment]
@dlddnd 감사합니다😀 이부분은 구체적으로 그렇다고 답변드리기가 어렵습니다(테스트케이스가  소수이기 때문입니다🥺)
테스트 도중 지도에서표시된 병원보다는 조금 떨어진 곳에서도 잡히는 것 같기는 합니다.( 엄청멀리는 아닙니다) 
쉽게 생각하면 이 프로그램은 사람이 직접 웹에서 업데이트 버튼을 클릭하고, 병원을 예약하는 것과 같은 효과를 가져오도록 작동합니다!:)

**Comment by dlddnd** [comment]
아 그런 것 같네용 목록보기를 눌러보면 지도상에 표시된 병원들 외의 병원들도 목록에 있네요. 아마 그 병원들에서 백신이 발생해도 잡히는 것 같네요

**Comment by narongchan** [comment]
@dlddnd 말씀해주신것처럼 있는 병원들에서 잡힐 겁니다:)
